### ISSUE TITLE
SEARCHING IS NOT DONE

### ISSUE THREAD

**Issue by stebenc** [k----n/AirlineBooking#1]
**SEARCHING INPUT**
- [x] Search for source and destination
- [x] Search input is case insensitive
- [x]  Results for partial matching for user input of airport codes, airport names, and city 
- [x] Source
- [x] Destination
- [x] Departure date

**SEARCHING OUTPUT**
- [x] _QUERY RESULTS_
  - [x] flight number
  - [x] source airport code
  - [x] destination airport code
  - [x] departure time
  - [x] arrival time
  - [x] number of stops
  - [x] layover time for non-direct flights
  - [x] price
  - [x] number of seats at that price (?)
  - [x] sorted based off price from LOWEST to HIGHEST
- [x] Return flights between the source and destination on the given date(s) and have available seats
- [x] Include direct flights and flights with one connection (i.e two flights with a stop in between)
- [x] _SORTING_:
  User should have the option to sort result 
  - [x] based on the number of connections (with direct flights listed first) - **PRIMARY SORT CRITERION**
  - [x] price - **SECONDARY SORT CRITERION**

**NEW ISSUES**
-  [x] print distinct results
-  [x] print departure & arrival times for flights that have turnover

**Comment by k----n** [comment]
Fixed
